default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    # trims all whitespace from the end of each line
    -   id: trailing-whitespace
    # ensures that all files end in a newline and only a newline
    -   id: end-of-file-fixer
    # prevents large files from being committed (>100kb)
    -   id: check-added-large-files
        args: [--maxkb=100]
    # enforce the naming conventions of test scripts
    -   id: name-tests-test
        # tests match test_.*\.py
        args: [--pytest-test-first]

-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.23.0
    hooks:
    -   id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

-   repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
    -   id: isort
        additional_dependencies: [toml]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
    -   id: ruff-check
    -   id: ruff-format
